# Generated by Django 5.1.3 on 2025-01-13 15:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Lenovo\\Desktop\\Django\\Projects\\Dominos_Clone\\media'), upload_to='round/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
