# Generated by Django 5.1.3 on 2025-01-13 15:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Lenovo\\Desktop\\Django\\Projects\\Dominos_Clone\\media'), upload_to='slide/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
