# Generated by Django 5.1.3 on 2025-01-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='df',
            field=models.IntegerField(default=40),
        ),
    ]
