# Generated by Django 5.1.3 on 2025-01-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_df'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='df',
        ),
    ]
