# Generated by Django 5.1.3 on 2025-01-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_otp_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
